server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: core-retail-ledger-engine
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  # Redis In-Memory Validation & Idempotency Configuration
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6380}
      timeout: 5000ms

  # Asynchronous Kafka Streaming Configuration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: core-ledger-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: all
      properties:
        enable.idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Dual Datasource Configuration (Oracle Master + Postgres Immutable Audit)
app:
  datasource:
    oracle:
      url: ${ORACLE_URL:jdbc:h2:mem:ledgerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle}
      driver-class-name: ${ORACLE_DRIVER:org.h2.Driver}
      username: ${ORACLE_USER:sa}
      password: ${ORACLE_PASSWORD:}
      hikari:
        maximum-pool-size: 30
        minimum-idle: 5
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 5000
        pool-name: OracleMasterPool
    postgres:
      url: ${POSTGRES_URL:jdbc:h2:mem:ledgerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL}
      driver-class-name: ${POSTGRES_DRIVER:org.h2.Driver}
      username: ${POSTGRES_USER:sa}
      password: ${POSTGRES_PASSWORD:}
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 5000
        pool-name: PostgresAuditPool
  security:
    jwt-secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    jwt-expiration-ms: 86400000 # 24 Hours
  reconciliation:
    cron: "0 */15 * * * *"

# Actuator & OpenTelemetry Prometheus Metrics
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        ledger.mutation.latency: true
        ledger.idempotency.check: true
        ledger.token.check: true
