-- =============================================================================
-- Oracle XE Schema — Bank Ledger (ledger_master user / XEPDB1)
-- Used by: auth-service, account-service, transaction-service,
--          outbox-publisher, reconciliation-service
-- =============================================================================

-- -----------------------------------------------------------------------------
-- CUSTOMER
-- Shared by auth-service (login) and account-service (profile reads)
-- -----------------------------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CUSTOMER (
    customer_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(50)  NOT NULL,
    password_hash  VARCHAR2(255) NOT NULL,
    first_name     VARCHAR2(100) NOT NULL,
    last_name      VARCHAR2(100) NOT NULL,
    email          VARCHAR2(150) NOT NULL,
    contact_no     VARCHAR2(30)  NOT NULL,
    status         VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    created_date   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_customer_username UNIQUE (username),
    CONSTRAINT uq_customer_email    UNIQUE (email),
    CONSTRAINT ck_customer_status   CHECK  (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE INDEX idx_customer_username ON CUSTOMER (username);
CREATE INDEX idx_customer_email    ON CUSTOMER (email);

-- -----------------------------------------------------------------------------
-- ACCOUNT
-- Used by account-service and transaction-service
-- -----------------------------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ACCOUNT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE ACCOUNT (
    account_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     NUMBER(19)     NOT NULL,
    account_number  VARCHAR2(30)   NOT NULL,
    account_type    VARCHAR2(30)   NOT NULL,
    currency        VARCHAR2(10)   DEFAULT 'PHP' NOT NULL,
    current_balance NUMBER(18,4)   DEFAULT 0 NOT NULL,
    status          VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
    created_date    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_account_number   UNIQUE (account_number),
    CONSTRAINT fk_account_customer FOREIGN KEY (customer_id) REFERENCES CUSTOMER (customer_id),
    CONSTRAINT ck_account_status   CHECK  (status IN ('ACTIVE', 'INACTIVE', 'CLOSED', 'FROZEN')),
    CONSTRAINT ck_account_balance  CHECK  (current_balance >= 0)
);

CREATE INDEX idx_account_customer_id ON ACCOUNT (customer_id);
CREATE INDEX idx_account_status      ON ACCOUNT (status);

-- -----------------------------------------------------------------------------
-- TRANSACTION
-- Used by transaction-service and reconciliation-service (read)
-- -----------------------------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "TRANSACTION" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE "TRANSACTION" (
    transaction_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account_id  NUMBER(19)    NULL,
    to_account_id    NUMBER(19)    NULL,
    amount           NUMBER(18,4)  NOT NULL,
    source_currency  VARCHAR2(10)  DEFAULT 'PHP' NOT NULL,
    target_currency  VARCHAR2(10)  DEFAULT 'PHP' NOT NULL,
    transaction_type VARCHAR2(50)  NOT NULL,
    reference_no     VARCHAR2(100) NOT NULL,
    status           VARCHAR2(30)  DEFAULT 'PENDING' NOT NULL,
    failure_reason   VARCHAR2(500) NULL,
    transaction_date TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_transaction_ref    UNIQUE (reference_no),
    CONSTRAINT ck_transaction_status CHECK  (status IN ('PENDING','COMPLETED','FAILED','REVERSED'))
);

CREATE INDEX idx_txn_from_account  ON "TRANSACTION" (from_account_id);
CREATE INDEX idx_txn_to_account    ON "TRANSACTION" (to_account_id);
CREATE INDEX idx_txn_status        ON "TRANSACTION" (status);
CREATE INDEX idx_txn_date          ON "TRANSACTION" (transaction_date);

-- -----------------------------------------------------------------------------
-- OUTBOX_EVENT
-- Written by transaction-service inside its ACID commit.
-- Polled and updated by outbox-publisher.
-- -----------------------------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE OUTBOX_EVENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE OUTBOX_EVENT (
    event_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  NUMBER(19)   NOT NULL,
    event_type      VARCHAR2(50) NOT NULL,
    payload         CLOB         NOT NULL,
    status          VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    created_date    TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    processed_date  TIMESTAMP    NULL,
    CONSTRAINT ck_outbox_status CHECK (status IN ('PENDING','PROCESSED','FAILED','DEAD_LETTER'))
);

CREATE INDEX idx_outbox_status       ON OUTBOX_EVENT (status);
CREATE INDEX idx_outbox_txn_id       ON OUTBOX_EVENT (transaction_id);
CREATE INDEX idx_outbox_created_date ON OUTBOX_EVENT (created_date);

-- -----------------------------------------------------------------------------
-- AUDIT_LOG
-- Written by transaction-service for every operation
-- -----------------------------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUDIT_LOG (
    audit_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER(19)     NULL,
    action      VARCHAR2(100)  NOT NULL,
    entity      VARCHAR2(100)  NOT NULL,
    details     VARCHAR2(4000) NULL,
    "TIMESTAMP" TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_log_customer  ON AUDIT_LOG (customer_id);
CREATE INDEX idx_audit_log_timestamp ON AUDIT_LOG ("TIMESTAMP");

-- =============================================================================
-- End of Oracle schema
-- =============================================================================
