spring:
  config:
    activate:
      on-profile: docker

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: false
        jdbc:
          batch_size: 50

  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:29092

app:
  datasource:
    oracle:
      url: jdbc:oracle:thin:@oracle-xe:1521/XEPDB1
      driver-class-name: oracle.jdbc.OracleDriver
      username: ledger_master
      password: MasterSecretPassword123
